language: node_js
node_js:
- '8'
branches:
  only:
  - hexo
before_install:
- npm install hexo-cli -g

install:
- npm install

script:
  - hexo clean
  - hexo generate

after_script:
  - git config user.name "zpr1g"
  - git config user.email "yuns.xie@qq.com"
  # 替换同目录下的_config.yml文件中gh_token字符串为travis后台刚才配置的变量，注意此处sed命令用了双引号。单引号无效！
  - sed -i "s/github_token/${GITHUB_TOKEN}/g" ./_config.yml
  - hexo deploy

cache:
  directories:
  - node_modules
